//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPWEBAccessControl
{


	public partial class DocMgtView
	{

		/// <summary>
		/// UpdatePanel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.UpdatePanel UpdatePanel;

		/// <summary>
		/// dataUpdatePanel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl dataUpdatePanel;

		/// <summary>
		/// lblfrmName control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label lblfrmName;

		/// <summary>
		/// TreeView1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TreeView TreeView1;

		/// <summary>
		/// Master property.
		/// </summary>
		/// <remarks>
		/// Auto-generated property.
		/// </remarks>
		public new BPWEBAccessControl.SiteApp Master
		{
			get
			{
				return ((BPWEBAccessControl.SiteApp)(base.Master));
			}
		}
	}
}
